version: '3.7'
services:
  mocklogin:
    image: lblod/mock-login-service:0.7.0
    environment:
      GROUP_TYPE: "http://www.w3.org/ns/org#Organization"
  frontend:
    restart: "no"
    environment:
      EMBER_FEATURE_PUBLIC_SERVICES_ENABLED: "true"
      EMBER_FEATURE_EREDIENSTEN_MANDATENBEHEER_ENABLED: "true"
      EMBER_FEATURE_WORSHIP_MINISTER_MANAGEMENT_ENABLED: "true"
      EMBER_WORSHIP_DECISIONS_DATABASE_URL: "https://dev.databankerediensten.lokaalbestuur.lblod.info"
      EMBER_WORSHIP_ORGANISATIONS_DATABASE_URL: "https://dev.organisaties.lokaalbestuur.lblod.info"
  identifier:
    ports:
      - "90:80"
    restart: "no"
  dispatcher:
    restart: "no"
  database:
    restart: "no"
  virtuoso:
    ports:
      - "8890:8890"
    restart: "no"
  deltanotifier:
    restart: "no"
  migrations:
    restart: "no"
  cache:
    restart: "no"
  resource:
    restart: "no"
  file:
    restart: "no"
  subsidy-applications-management:
    environment:
      VERSIONED_CONFIGURATION_WATCHER: null
    restart: "no"
  subsidy-application-flow-management:
    restart: "no"