PREFIX mobiliteit: <https://data.vlaanderen.be/ns/mobiliteit#>
PREFIX lblodSubsidie: <http://lblod.data.gift/vocabularies/subsidie/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX subsidie: <http://data.vlaanderen.be/ns/subsidie#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX cpsv: <http://purl.org/vocab/cpsv#>
PREFIX xkos: <http://rdf-vocabulary.ddialliance.org/xkos#>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    # add follows reference to the subsidy measure offer
    <http://lblod.data.info/id/subsidy-measure-offers/d568b824-b531-4400-bf91-91dc2296be31> cpsv:follows <http://data.lblod.info/id/subsidy-procedural-steps/a691a797-9a90-458a-bc8b-8dfc5e627c25> .

    # add link from subsidy-measure-offer-series to subsidy-procedural-step
    <http://lblod.data.info/id/subsidy-measure-offer-series/605480ce-554e-4d80-b310-249366157674> lblodSubsidie:heeftSubsidieprocedurestap <http://data.lblod.info/id/subsidy-procedural-steps/a691a797-9a90-458a-bc8b-8dfc5e627c25>.

    # create new subsidie-application-flow-step
    <http://lblod.data.info/id/subsidie-application-flow-steps/d3f29901-be52-4ec2-84c6-fd281780187f> a lblodSubsidie:ApplicationStep;
      mu:uuid "d3f29901-be52-4ec2-84c6-fd281780187f";
      qb:order 3;
      xkos:previous  <http://lblod.data.info/id/subsidie-application-flow-steps/3514ae35-e18e-48b5-8647-80c06d926c78>;
      dct:references <http://data.lblod.info/id/subsidy-procedural-steps/a691a797-9a90-458a-bc8b-8dfc5e627c25> ;
      dct:isPartOf <http://lblod.data.info/id/subsidie-application-flows/18876ca3-4cab-4598-9054-d6a705b2a5fb>; #this should be the application-flow of climate
      dct:source <config://forms/peloton/documenten/versions/20240916154447/form.ttl>.

    # Create new subsidy-procedural-step
    <http://data.lblod.info/id/subsidy-procedural-steps/a691a797-9a90-458a-bc8b-8dfc5e627c25> a subsidie:Subsidieprocedurestap;
      mu:uuid "a691a797-9a90-458a-bc8b-8dfc5e627c25";
      dct:description """Documenten""";
      mobiliteit:periode <http://data.lblod.info/id/periodes/00dbd6ca-7a41-4c17-ac59-b2252936270d>.

    # Tell previous step that this new step is it's next step
    <http://lblod.data.info/id/subsidie-application-flow-steps/6d6e5a1d-53fd-4e42-8d41-94dec6f39c68> xkos:next <http://lblod.data.info/id/subsidie-application-flow-steps/d3f29901-be52-4ec2-84c6-fd281780187f>.
  }
}