PREFIX mobiliteit: <https://data.vlaanderen.be/ns/mobiliteit#>
PREFIX lblodSubsidie: <http://lblod.data.gift/vocabularies/subsidie/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX subsidie: <http://data.vlaanderen.be/ns/subsidie#>
PREFIX gleif: <https://www.gleif.org/ontology/Base/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX cpsv: <http://purl.org/vocab/cpsv#>
PREFIX common: <http://www.w3.org/2007/uwa/context/common.owl#>
PREFIX xkos: <http://rdf-vocabulary.ddialliance.org/xkos#>
PREFIX qb: <http://purl.org/linked-data/cube#>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public>{
    <http://lblod.data.info/id/subsidy-measure-offers/d568b824-b531-4400-bf91-91dc2296be31>
      a <http://data.vlaanderen.be/ns/subsidie#SubsidiemaatregelAanbod>;
      mu:uuid "d568b824-b531-4400-bf91-91dc2296be31";
      dct:title """Peloton""";
      skos:prefLabel """Peloton""";
      skos:related <https://nl.wikipedia.org/wiki/Peloton_(wielrennen)>;
      cpsv:follows <http://data.lblod.info/id/subsidy-procedural-steps/9fb8b3f3-12ef-47ef-a7cf-efbfdedba4cb>;
      lblodSubsidie:heeftReeks <http://lblod.data.info/id/subsidy-measure-offer-series/605480ce-554e-4d80-b310-249366157674>.

    <http://data.lblod.info/id/subsidy-procedural-steps/9fb8b3f3-12ef-47ef-a7cf-efbfdedba4cb> a subsidie:Subsidieprocedurestap;
      mu:uuid "9fb8b3f3-12ef-47ef-a7cf-efbfdedba4cb";
      dct:description """Aanvraag""";
      mobiliteit:periode <http://data.lblod.info/id/periodes/d9ef7dd4-ae9b-43d4-b762-a31425fc45c9>.

    <http://lblod.data.info/id/subsidy-measure-offer-series/605480ce-554e-4d80-b310-249366157674> a lblodSubsidie:SubsidiemaatregelAanbodReeks;
      mu:uuid "605480ce-554e-4d80-b310-249366157674";
      dct:title "Oproep 2024"@nl;
      dct:description "01/01/2024 — 01/01/2028"@nl ;
      common:active <http://lblod.data.info/id/subsidie-application-flows/18876ca3-4cab-4598-9054-d6a705b2a5fb> ;
      mobiliteit:periode <http://data.lblod.info/id/periodes/00dbd6ca-7a41-4c17-ac59-b2252936270d> ;
      lblodSubsidie:heeftSubsidieprocedurestap <http://data.lblod.info/id/subsidy-procedural-steps/9fb8b3f3-12ef-47ef-a7cf-efbfdedba4cb>.

    <http://lblod.data.info/id/subsidie-application-flows/18876ca3-4cab-4598-9054-d6a705b2a5fb> a lblodSubsidie:ApplicationFlow;
      mu:uuid "18876ca3-4cab-4598-9054-d6a705b2a5fb";
      xkos:belongsTo <http://lblod.data.info/id/subsidy-measure-offer-series/605480ce-554e-4d80-b310-249366157674>;
      xkos:next <http://lblod.data.info/id/subsidie-application-flow-steps/1e94f1ba-9636-4174-99a4-c0750f806b19>.

    <http://lblod.data.info/id/subsidie-application-flow-steps/1e94f1ba-9636-4174-99a4-c0750f806b19> a lblodSubsidie:ApplicationStep;
      mu:uuid "1e94f1ba-9636-4174-99a4-c0750f806b19";
      qb:order 0;
      dct:references <http://data.lblod.info/id/subsidy-procedural-steps/9fb8b3f3-12ef-47ef-a7cf-efbfdedba4cb>;
      dct:isPartOf <http://lblod.data.info/id/subsidie-application-flows/18876ca3-4cab-4598-9054-d6a705b2a5fb>;
      dct:source <config://forms/peloton/aanvraag/versions/20240916154447/form.ttl>.

    <http://data.lblod.info/id/periodes/00dbd6ca-7a41-4c17-ac59-b2252936270d> a <http://data.europa.eu/m8g/PeriodOfTime>;
      mu:uuid "00dbd6ca-7a41-4c17-ac59-b2252936270d";
      <http://data.europa.eu/m8g/startTime> "2024-01-01T03:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>;
      <http://data.europa.eu/m8g/endTime> "2028-01-01T21:59:59Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>.

    <http://data.lblod.info/id/periodes/d9ef7dd4-ae9b-43d4-b762-a31425fc45c9> a <http://data.europa.eu/m8g/PeriodOfTime>;
      mu:uuid "d9ef7dd4-ae9b-43d4-b762-a31425fc45c9";
      <http://data.europa.eu/m8g/startTime> "2024-01-01T00:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>;
      <http://data.europa.eu/m8g/endTime> "2028-01-01T21:59:59Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>.
  }
}
